name: Pull Request
description: Template for pull requests
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of changes
      placeholder: What changes does this PR introduce?
    validations:
      required: true
  - type: checkboxes
    id: type
    attributes:
      label: Type of Change
      options:
        - label: Bug fix
        - label: New feature
        - label: Refactoring
        - label: Documentation
    validations:
      required: true
  - type: checkboxes
    id: testing
    attributes:
      label: Testing
      options:
        - label: Tests pass
        - label: Manual testing done
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Code follows project style
        - label: Self-review completed
        - label: Tests added/updated
