name: Bug Report
description: Report a bug.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the bug.
      placeholder: What is the bug...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the bug
      placeholder: What steps did you take to reproduce the bug...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe your expected behavior...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe your actual behavior...
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g., macOS 14.0...
