name: New Feature
description: Suggest a new feature.
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the feature.
      placeholder: What feature do you want...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: What problem are you trying to solve...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: How should it work?
      placeholder: Describe your proposed solution...
    validations:
      required: true
